import { slugify } from "./roms";

export type Series = { title: string; models: string[] };
export type Brand = { slug: string; name: string; series: Series[] };

export const BRANDS: Brand[] = [
  {
    slug: "pixel",
    name: "Google Pixel",
    series: [
      {
        title: "PIXEL",
        models: [
          "Pixel 10 Pro XL",
          "Pixel 10 Pro",
          "Pixel 10",
          "Pixel 9a",
          "Pixel 9 Pro Fold",
          "Pixel 9 Pro XL",
          "Pixel 9 Pro",
          "Pixel 9",
          "Pixel 8a",
          "Pixel 8 Pro",
          "Pixel 8",
          "Pixel 7a",
          "Pixel 7 Pro",
          "Pixel 7",
          "Pixel 6a",
          "Pixel 6 Pro",
          "Pixel 6",
          "Pixel 5a",
          "Pixel 5",
          "Pixel 4a 5G",
          "Pixel 4a",
          "Pixel 4 XL",
          "Pixel 4",
          "Pixel 3a XL",
          "Pixel 3a",
          "Pixel 3 XL",
          "Pixel 3",
          "Pixel 2 XL",
          "Pixel 2",
          "Pixel XL",
          "Pixel",
        ],
      },
    ],
  },
  {
    slug: "samsung",
    name: "Samsung",
    series: [
      {
        title: "GALAXY S",
        models: [
          "Galaxy S",
          "Galaxy S Plus",
          "Galaxy S2",
          "Galaxy S2 Plus",
          "Galaxy S3",
          "Galaxy S3 Mini",
          "Galaxy S4",
          "Galaxy S4 Mini",
          "Galaxy S4 Active",
          "Galaxy S4 Zoom",
          "Galaxy S5",
          "Galaxy S5 Mini",
          "Galaxy S5 Active",
          "Galaxy S5 Sport",
          "Galaxy S6",
          "Galaxy S6 Edge",
          "Galaxy S6 Edge+",
          "Galaxy S6 Active",
          "Galaxy S7",
          "Galaxy S7 Edge",
          "Galaxy S7 Active",
          "Galaxy S8",
          "Galaxy S8+",
          "Galaxy S8 Active",
          "Galaxy S9",
          "Galaxy S9+",
          "Galaxy S10e",
          "Galaxy S10",
          "Galaxy S10+",
          "Galaxy S10 5G",
          "Galaxy S10 Lite",
          "Galaxy S20",
          "Galaxy S20+",
          "Galaxy S20 Ultra",
          "Galaxy S20 FE",
          "Galaxy S20 FE 5G",
          "Galaxy S21",
          "Galaxy S21+",
          "Galaxy S21 Ultra",
          "Galaxy S21 FE",
          "Galaxy S22",
          "Galaxy S22+",
          "Galaxy S22 Ultra",
          "Galaxy S23",
          "Galaxy S23+",
          "Galaxy S23 Ultra",
          "Galaxy S23 FE",
          "Galaxy S24",
          "Galaxy S24+",
          "Galaxy S24 Ultra",
          "Galaxy S24 FE",
          "Galaxy S25",
          "Galaxy S25+",
          "Galaxy S25 Ultra",
          "Galaxy S25 Edge",
          "Galaxy S25 FE",
          "Galaxy S26",
          "Galaxy S26+",
          "Galaxy S26 Ultra",
        ],
      },
      {
        title: "GALAXY NOTE",
        models: [
          "Galaxy Note",
          "Galaxy Note II",
          "Galaxy Note 3",
          "Galaxy Note 3 Neo",
          "Galaxy Note 4",
          "Galaxy Note Edge",
          "Galaxy Note 5",
          "Galaxy Note 7",
          "Galaxy Note FE",
          "Galaxy Note 8",
          "Galaxy Note 9",
          "Galaxy Note 10",
          "Galaxy Note 10+",
          "Galaxy Note 10+ 5G",
          "Galaxy Note 20",
          "Galaxy Note 20 Ultra",
          "Galaxy Note 20 Ultra 5G",
        ],
      },
      {
        title: "GALAXY Z FOLD",
        models: [
          "Galaxy Fold",
          "Galaxy Z Fold2",
          "Galaxy Z Fold3",
          "Galaxy Z Fold4",
          "Galaxy Z Fold5",
          "Galaxy Z Fold6",
          "Galaxy Z Fold6 Special Edition",
          "Galaxy Z Fold7",
          "Galaxy Z Fold8",
        ],
      },
      {
        title: "GALAXY Z FLIP",
        models: [
          "Galaxy Z Flip",
          "Galaxy Z Flip 5G",
          "Galaxy Z Flip3",
          "Galaxy Z Flip4",
          "Galaxy Z Flip5",
          "Galaxy Z Flip6",
          "Galaxy Z Flip7",
          "Galaxy Z Flip7 FE",
          "Galaxy Z Flip8",
        ],
      },
      {
        title: "GALAXY A",
        models: [
          "Galaxy A3",
          "Galaxy A5",
          "Galaxy A7",
          "Galaxy A8",
          "Galaxy A8+",
          "Galaxy A9",
          "Galaxy A9 Pro",
          "Galaxy A3 (2017)",
          "Galaxy A5 (2017)",
          "Galaxy A7 (2017)",
          "Galaxy A6",
          "Galaxy A6+",
          "Galaxy A8 (2018)",
          "Galaxy A8+ (2018)",
          "Galaxy A8 Star",
          "Galaxy A9 (2018)",
          "Galaxy A10",
          "Galaxy A10e",
          "Galaxy A10s",
          "Galaxy A20",
          "Galaxy A20e",
          "Galaxy A20s",
          "Galaxy A30",
          "Galaxy A30s",
          "Galaxy A40",
          "Galaxy A50",
          "Galaxy A50s",
          "Galaxy A60",
          "Galaxy A70",
          "Galaxy A70s",
          "Galaxy A80",
          "Galaxy A90 5G",
          "Galaxy A01",
          "Galaxy A01 Core",
          "Galaxy A11",
          "Galaxy A21",
          "Galaxy A21s",
          "Galaxy A31",
          "Galaxy A41",
          "Galaxy A51",
          "Galaxy A51 5G",
          "Galaxy A71",
          "Galaxy A71 5G",
          "Galaxy A02",
          "Galaxy A02s",
          "Galaxy A12",
          "Galaxy A22",
          "Galaxy A22 5G",
          "Galaxy A32",
          "Galaxy A32 5G",
          "Galaxy A42 5G",
          "Galaxy A52",
          "Galaxy A52 5G",
          "Galaxy A52s 5G",
          "Galaxy A72",
          "Galaxy A03",
          "Galaxy A03 Core",
          "Galaxy A03s",
          "Galaxy A13",
          "Galaxy A13 5G",
          "Galaxy A23",
          "Galaxy A23 5G",
          "Galaxy A33 5G",
          "Galaxy A53 5G",
          "Galaxy A73 5G",
          "Galaxy A04",
          "Galaxy A04e",
          "Galaxy A04s",
          "Galaxy A14",
          "Galaxy A14 5G",
          "Galaxy A24",
          "Galaxy A34 5G",
          "Galaxy A54 5G",
          "Galaxy A05",
          "Galaxy A05s",
          "Galaxy A15",
          "Galaxy A15 5G",
          "Galaxy A25 5G",
          "Galaxy A16",
          "Galaxy A16 5G",
          "Galaxy A35 5G",
          "Galaxy A55 5G",
          "Galaxy A06",
          "Galaxy A06 5G",
          "Galaxy A26 5G",
          "Galaxy A36 5G",
          "Galaxy A56 5G",
          "Galaxy A07",
          "Galaxy A17",
          "Galaxy A27",
          "Galaxy A37",
          "Galaxy A57",
        ],
      },
      {
        title: "SAMSUNG TABS",
        models: [
          "Galaxy Tab S11 Ultra",
          "Galaxy Tab S11+",
          "Galaxy Tab S11",
          "Galaxy Tab S10 Ultra",
          "Galaxy Tab S10+",
          "Galaxy Tab S10 FE+",
          "Galaxy Tab S10 FE",
          "Galaxy Tab S9 Ultra",
          "Galaxy Tab S9+",
          "Galaxy Tab S9",
          "Galaxy Tab S9 FE+",
          "Galaxy Tab S9 FE",
          "Galaxy Tab S8 Ultra",
          "Galaxy Tab S8+",
          "Galaxy Tab S8",
          "Galaxy Tab S8 FE",
          "Galaxy Tab S7+",
          "Galaxy Tab S7",
          "Galaxy Tab S7 FE",
          "Galaxy Tab S6",
          "Galaxy Tab S6 Lite",
          "Galaxy Tab S5e",
          "Galaxy Tab S4",
          "Galaxy Tab S3",
          "Galaxy Tab S2",
          "Galaxy Tab S",
          "Galaxy Tab A9+",
          "Galaxy Tab A9",
          "Galaxy Tab A8",
          "Galaxy Tab A7",
          "Galaxy Tab A7 Lite",
          "Galaxy Tab A 10.1",
          "Galaxy Tab A 8.0",
          "Galaxy Tab A",
          "Galaxy Tab Active5 Pro",
          "Galaxy Tab Active5",
          "Galaxy Tab Active3",
          "Galaxy Tab Active Pro",
          "Galaxy Tab Active2",
          "Galaxy Tab Active",
          "Galaxy Tab Pro",
          "Galaxy Tab 4",
          "Galaxy Tab 3",
          "Galaxy Tab 2",
          "Galaxy Tab",
        ],
      },
    ],
  },
  {
    slug: "xiaomi",
    name: "Xiaomi",
    series: [
      {
        title: "XIAOMI FLAGSHIPS",
        models: [
          "Xiaomi 17 Ultra",
          "Xiaomi 17 Pro Max",
          "Xiaomi 17 Pro",
          "Xiaomi 17",
          "Xiaomi 16 Ultra",
          "Xiaomi 16 Pro",
          "Xiaomi 16",
          "Xiaomi 15 Ultra",
          "Xiaomi 15 Pro",
          "Xiaomi 15",
          "Xiaomi 14 Ultra",
          "Xiaomi 14 Pro",
          "Xiaomi 14",
          "Xiaomi 13 Ultra",
          "Xiaomi 13 Pro",
          "Xiaomi 13",
          "Xiaomi 12S Ultra",
          "Xiaomi 12S Pro",
          "Xiaomi 12S",
          "Xiaomi 12 Pro",
          "Xiaomi 12",
          "Xiaomi 11 Ultra",
          "Xiaomi 11 Pro",
          "Xiaomi 11",
        ],
      },
      {
        title: "MI SERIES",
        models: [
          "Mi 10 Ultra",
          "Mi 10 Pro",
          "Mi 10",
          "Mi 9",
          "Mi 8",
          "Mi 6",
          "Mi 5",
          "Mi 4",
          "Mi 3",
          "Mi 2",
          "Mi 1",
        ],
      },
      {
        title: "XIAOMI TABLETS",
        models: [
          "Xiaomi Pad 8 Ultra",
          "Xiaomi Pad 8 Pro",
          "Xiaomi Pad 8",
          "Xiaomi Pad 7 Ultra",
          "Xiaomi Pad 7 Pro",
          "Xiaomi Pad 7",
          "Xiaomi Pad 6S Pro 12.4",
          "Xiaomi Pad 6 Pro",
          "Xiaomi Pad 6",
          "Xiaomi Pad 5 Pro 12.4",
          "Xiaomi Pad 5 Pro",
          "Xiaomi Pad 5",
          "Xiaomi Pad 4 Plus",
          "Xiaomi Pad 4",
          "Xiaomi Pad 3",
          "Xiaomi Pad 2",
          "Xiaomi Mi Pad",
        ],
      },
    ],
  },
  {
    slug: "redmi",
    name: "Redmi",
    series: [
      {
        title: "REDMI NOTE",
        models: [
          "Redmi Note 15 Pro+ 5G",
          "Redmi Note 15 Pro 5G",
          "Redmi Note 15 5G",
          "Redmi Note 14 Pro+ 5G",
          "Redmi Note 14 Pro 5G",
          "Redmi Note 14 Pro",
          "Redmi Note 14 5G",
          "Redmi Note 14",
          "Redmi Note 13 Pro+ 5G",
          "Redmi Note 13 Pro 5G",
          "Redmi Note 13 Pro",
          "Redmi Note 13 5G",
          "Redmi Note 13",
          "Redmi Note 12 Pro+ 5G",
          "Redmi Note 12 Pro 5G",
          "Redmi Note 12 Pro",
          "Redmi Note 12 5G",
          "Redmi Note 12",
          "Redmi Note 11 Pro+ 5G",
          "Redmi Note 11 Pro 5G",
          "Redmi Note 11 Pro",
          "Redmi Note 11S",
          "Redmi Note 11 5G",
          "Redmi Note 11",
          "Redmi Note 10 Pro",
          "Redmi Note 10 5G",
          "Redmi Note 10",
          "Redmi Note 9 Pro",
          "Redmi Note 9S",
          "Redmi Note 9",
          "Redmi Note 8 Pro",
          "Redmi Note 8",
          "Redmi Note 7 Pro",
          "Redmi Note 7",
          "Redmi Note 6 Pro",
          "Redmi Note 5 Pro",
          "Redmi Note 5",
          "Redmi Note 4",
          "Redmi Note 3",
          "Redmi Note 2",
          "Redmi Note",
        ],
      },
    ],
  },
  {
    slug: "poco",
    name: "Poco",
    series: [
      {
        title: "POCO F",
        models: [
          "POCO F7 Ultra",
          "POCO F7 Pro",
          "POCO F7",
          "POCO F6 Pro",
          "POCO F6",
          "POCO F5 Pro",
          "POCO F5",
          "POCO F4 GT",
          "POCO F4",
          "POCO F3 GT",
          "POCO F3",
          "POCO F2 Pro",
          "POCO F1",
        ],
      },
      {
        title: "POCO X",
        models: [
          "POCO X7 Pro",
          "POCO X7",
          "POCO X6 Pro",
          "POCO X6",
          "POCO X5 Pro 5G",
          "POCO X5 5G",
          "POCO X4 Pro 5G",
          "POCO X4 GT",
          "POCO X3 Pro",
          "POCO X3 NFC",
          "POCO X3",
          "POCO X2",
        ],
      },
      {
        title: "POCO M",
        models: [
          "POCO M7 Pro 5G",
          "POCO M7",
          "POCO M6 Pro",
          "POCO M6",
          "POCO M5s",
          "POCO M5",
          "POCO M4 Pro 5G",
          "POCO M4 Pro",
          "POCO M4 5G",
          "POCO M3 Pro 5G",
          "POCO M3",
          "POCO M2 Pro",
          "POCO M2",
        ],
      },
      {
        title: "POCO C",
        models: ["POCO C75", "POCO C65", "POCO C55", "POCO C40", "POCO C31", "POCO C3"],
      },
    ],
  },
  {
    slug: "oneplus",
    name: "OnePlus",
    series: [
      {
        title: "ONEPLUS",
        models: [
          "OnePlus 15",
          "OnePlus 13",
          "OnePlus 13R",
          "OnePlus 12",
          "OnePlus 12R",
          "OnePlus 11",
          "OnePlus 11R",
          "OnePlus 10 Pro",
          "OnePlus 10T",
          "OnePlus 10R",
          "OnePlus 9 Pro",
          "OnePlus 9",
          "OnePlus 9R",
          "OnePlus 8 Pro",
          "OnePlus 8T",
          "OnePlus 8",
          "OnePlus 7T Pro",
          "OnePlus 7T",
          "OnePlus 7 Pro",
          "OnePlus 7",
          "OnePlus 6T",
          "OnePlus 6",
          "OnePlus 5T",
          "OnePlus 5",
          "OnePlus 3T",
          "OnePlus 3",
          "OnePlus 2",
          "OnePlus One",
        ],
      },
    ],
  },
  {
    slug: "motorola",
    name: "Motorola",
    series: [
      {
        title: "MOTOROLA RAZR",
        models: [
          "Motorola Razr 60 Ultra",
          "Motorola Razr 60",
          "Motorola Razr 50 Ultra",
          "Motorola Razr 50",
          "Motorola Razr 40 Ultra",
          "Motorola Razr 40",
          "Motorola Razr 2022",
          "Motorola Razr 5G",
          "Motorola Razr 2019",
        ],
      },
      {
        title: "MOTOROLA EDGE",
        models: [
          "Motorola Edge 60 Pro",
          "Motorola Edge 60",
          "Motorola Edge 50 Ultra",
          "Motorola Edge 50 Pro",
          "Motorola Edge 50 Fusion",
          "Motorola Edge 50 Neo",
          "Motorola Edge 40 Pro",
          "Motorola Edge 40",
          "Motorola Edge 40 Neo",
          "Motorola Edge 30 Ultra",
          "Motorola Edge 30 Pro",
          "Motorola Edge 30 Fusion",
          "Motorola Edge 30 Neo",
          "Motorola Edge 30",
          "Motorola Edge 20 Pro",
          "Motorola Edge 20",
          "Motorola Edge+",
          "Motorola Edge",
        ],
      },
      {
        title: "MOTO G",
        models: [
          "Moto G Power (2025)",
          "Moto G 2025",
          "Moto G75 5G",
          "Moto G85 5G",
          "Moto G84 5G",
          "Moto G73 5G",
          "Moto G72",
          "Moto G71 5G",
          "Moto G62 5G",
          "Moto G60",
          "Moto G50",
          "Moto G40 Fusion",
          "Moto G31",
          "Moto G30",
          "Moto G Power (2024)",
          "Moto G Power (2023)",
          "Moto G Power (2022)",
          "Moto G Power (2021)",
          "Moto G Power (2020)",
          "Moto G7 Power",
          "Moto G6",
        ],
      },
      {
        title: "MOTO E",
        models: [
          "Moto E15",
          "Moto E14",
          "Moto E13",
          "Moto E22",
          "Moto E32",
          "Moto E20",
          "Moto E7 Power",
          "Moto E7",
          "Moto E6",
          "Moto E5",
        ],
      },
    ],
  },
  {
    slug: "sony",
    name: "Sony",
    series: [
      {
        title: "XPERIA 1",
        models: [
          "Sony Xperia 1 VII",
          "Sony Xperia 1 VI",
          "Sony Xperia 1 V",
          "Sony Xperia 1 IV",
          "Sony Xperia 1 III",
          "Sony Xperia 1 II",
          "Sony Xperia 1",
        ],
      },
      {
        title: "XPERIA 5",
        models: [
          "Sony Xperia 5 V",
          "Sony Xperia 5 IV",
          "Sony Xperia 5 III",
          "Sony Xperia 5 II",
          "Sony Xperia 5",
        ],
      },
      {
        title: "XPERIA 10",
        models: [
          "Sony Xperia 10 VII",
          "Sony Xperia 10 VI",
          "Sony Xperia 10 V",
          "Sony Xperia 10 IV",
          "Sony Xperia 10 III",
          "Sony Xperia 10 II",
        ],
      },
      { title: "XPERIA PRO", models: ["Sony Xperia PRO-I", "Sony Xperia PRO"] },
      {
        title: "XPERIA XZ",
        models: [
          "Sony Xperia XZ3",
          "Sony Xperia XZ2 Premium",
          "Sony Xperia XZ2",
          "Sony Xperia XZ1",
          "Sony Xperia XZ Premium",
        ],
      },
      {
        title: "XPERIA CLASSICS",
        models: [
          "Sony Xperia X Performance",
          "Sony Xperia XZ",
          "Sony Xperia X Compact",
          "Sony Xperia X",
          "Sony Xperia XA2 Ultra",
          "Sony Xperia XA2",
          "Sony Xperia XA1 Ultra",
          "Sony Xperia XA1",
          "Sony Xperia Z5 Premium",
          "Sony Xperia Z5",
          "Sony Xperia Z3+",
          "Sony Xperia Z3",
          "Sony Xperia Z2",
          "Sony Xperia Z1",
          "Sony Xperia Z Ultra",
          "Sony Xperia Z",
        ],
      },
    ],
  },
  {
    slug: "nothing",
    name: "Nothing",
    series: [
      {
        title: "NOTHING PHONE",
        models: [
          "Nothing Phone (3a) Pro",
          "Nothing Phone (3a)",
          "Nothing Phone (3)",
          "Nothing Phone (2a) Plus",
          "Nothing Phone (2a)",
          "Nothing Phone (2)",
          "Nothing Phone (1)",
        ],
      },
      {
        title: "COMMUNITY EDITIONS",
        models: [
          "Nothing Phone (3a) Pro Community Edition",
          "Nothing Phone (2a) Community Edition",
        ],
      },
      { title: "NOTHING TABLETS", models: ["Nothing Tablet 1"] },
    ],
  },
  {
    slug: "asus",
    name: "Asus",
    series: [
      {
        title: "ZENFONE",
        models: [
          "ASUS Zenfone 12 Ultra",
          "ASUS Zenfone 11 Ultra",
          "ASUS Zenfone 10",
          "ASUS Zenfone 9",
          "ASUS Zenfone 8",
          "ASUS Zenfone 8 Flip",
          "ASUS Zenfone 7 Pro",
          "ASUS Zenfone 7",
          "ASUS Zenfone 6",
          "ASUS ZenFone 5Z",
          "ASUS ZenFone 5",
          "ASUS ZenFone 4 Pro",
          "ASUS ZenFone 4",
          "ASUS ZenFone 3 Deluxe",
          "ASUS ZenFone 3",
          "ASUS ZenFone 2",
        ],
      },
      {
        title: "ROG PHONE",
        models: [
          "ASUS ROG Phone 9 Pro",
          "ASUS ROG Phone 9",
          "ASUS ROG Phone 8 Pro",
          "ASUS ROG Phone 8",
          "ASUS ROG Phone 7 Ultimate",
          "ASUS ROG Phone 7",
          "ASUS ROG Phone 6D Ultimate",
          "ASUS ROG Phone 6D",
          "ASUS ROG Phone 6 Pro",
          "ASUS ROG Phone 6",
          "ASUS ROG Phone 5s Pro",
          "ASUS ROG Phone 5s",
          "ASUS ROG Phone 5 Pro",
          "ASUS ROG Phone 5",
          "ASUS ROG Phone 3",
          "ASUS ROG Phone 2",
          "ASUS ROG Phone",
          "ASUS ROG Phone 9 Pro Edition",
          "ASUS ROG Phone 8 Pro Edition",
        ],
      },
      {
        title: "ROG FLOW",
        models: ["ASUS ROG Flow Z13", "ASUS ROG Flow Z13 2025"],
      },
    ],
  },
];

export function getBrand(slug: string): Brand | undefined {
  return BRANDS.find((b) => b.slug === slug);
}

export function deviceNameFromSlug(brandSlug: string, modelSlug: string): string | undefined {
  const brand = getBrand(brandSlug);
  if (!brand) return undefined;
  for (const series of brand.series) {
    const match = series.models.find((m) => slugify(m) === modelSlug);
    if (match) return match;
  }
  return undefined;
}
