/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ArticlesIdRouteImport } from './routes/articles.$id'
import { Route as DevicesBrandRouteImport } from './routes/devices_.$brand'
import { Route as DevicesBrandModelRouteImport } from './routes/devices_.$brand_.$model'
import { Route as DevicesBrandModelRomRouteImport } from './routes/devices_.$brand_.$model_.$rom'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesBrandRoute = DevicesBrandRouteImport.update({
  id: '/devices_/$brand',
  path: '/devices/$brand',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesBrandModelRoute = DevicesBrandModelRouteImport.update({
  id: '/devices_/$brand_/$model',
  path: '/devices/$brand/$model',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesBrandModelRomRoute = DevicesBrandModelRomRouteImport.update({
  id: '/devices_/$brand_/$model_/$rom',
  path: '/devices/$brand/$model/$rom',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/devices/$brand': typeof DevicesBrandRoute
  '/devices/$brand/$model': typeof DevicesBrandModelRoute
  '/devices/$brand/$model/$rom': typeof DevicesBrandModelRomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/devices/$brand': typeof DevicesBrandRoute
  '/devices/$brand/$model': typeof DevicesBrandModelRoute
  '/devices/$brand/$model/$rom': typeof DevicesBrandModelRomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/devices_/$brand': typeof DevicesBrandRoute
  '/devices_/$brand_/$model': typeof DevicesBrandModelRoute
  '/devices_/$brand_/$model_/$rom': typeof DevicesBrandModelRomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devices'
    | '/sitemap.xml'
    | '/articles/$id'
    | '/devices/$brand'
    | '/devices/$brand/$model'
    | '/devices/$brand/$model/$rom'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/devices'
    | '/sitemap.xml'
    | '/articles/$id'
    | '/devices/$brand'
    | '/devices/$brand/$model'
    | '/devices/$brand/$model/$rom'
  id:
    | '__root__'
    | '/'
    | '/devices'
    | '/sitemap.xml'
    | '/articles/$id'
    | '/devices_/$brand'
    | '/devices_/$brand_/$model'
    | '/devices_/$brand_/$model_/$rom'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevicesRoute: typeof DevicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArticlesIdRoute: typeof ArticlesIdRoute
  DevicesBrandRoute: typeof DevicesBrandRoute
  DevicesBrandModelRoute: typeof DevicesBrandModelRoute
  DevicesBrandModelRomRoute: typeof DevicesBrandModelRomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices_/$brand': {
      id: '/devices_/$brand'
      path: '/devices/$brand'
      fullPath: '/devices/$brand'
      preLoaderRoute: typeof DevicesBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices_/$brand_/$model': {
      id: '/devices_/$brand_/$model'
      path: '/devices/$brand/$model'
      fullPath: '/devices/$brand/$model'
      preLoaderRoute: typeof DevicesBrandModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices_/$brand_/$model_/$rom': {
      id: '/devices_/$brand_/$model_/$rom'
      path: '/devices/$brand/$model/$rom'
      fullPath: '/devices/$brand/$model/$rom'
      preLoaderRoute: typeof DevicesBrandModelRomRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevicesRoute: DevicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArticlesIdRoute: ArticlesIdRoute,
  DevicesBrandRoute: DevicesBrandRoute,
  DevicesBrandModelRoute: DevicesBrandModelRoute,
  DevicesBrandModelRomRoute: DevicesBrandModelRomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
