/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DevicesSamsungRouteImport } from './routes/devices_.samsung'
import { Route as DevicesSamsungModelRouteImport } from './routes/devices_.samsung.$model'
import { Route as DevicesSamsungModelRomRouteImport } from './routes/devices_.samsung.$model.$rom'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesSamsungRoute = DevicesSamsungRouteImport.update({
  id: '/devices_/samsung',
  path: '/devices/samsung',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesSamsungModelRoute = DevicesSamsungModelRouteImport.update({
  id: '/$model',
  path: '/$model',
  getParentRoute: () => DevicesSamsungRoute,
} as any)
const DevicesSamsungModelRomRoute = DevicesSamsungModelRomRouteImport.update({
  id: '/$rom',
  path: '/$rom',
  getParentRoute: () => DevicesSamsungModelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/devices/samsung': typeof DevicesSamsungRouteWithChildren
  '/devices/samsung/$model': typeof DevicesSamsungModelRouteWithChildren
  '/devices/samsung/$model/$rom': typeof DevicesSamsungModelRomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/devices/samsung': typeof DevicesSamsungRouteWithChildren
  '/devices/samsung/$model': typeof DevicesSamsungModelRouteWithChildren
  '/devices/samsung/$model/$rom': typeof DevicesSamsungModelRomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/devices_/samsung': typeof DevicesSamsungRouteWithChildren
  '/devices_/samsung/$model': typeof DevicesSamsungModelRouteWithChildren
  '/devices_/samsung/$model/$rom': typeof DevicesSamsungModelRomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devices'
    | '/sitemap.xml'
    | '/devices/samsung'
    | '/devices/samsung/$model'
    | '/devices/samsung/$model/$rom'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/devices'
    | '/sitemap.xml'
    | '/devices/samsung'
    | '/devices/samsung/$model'
    | '/devices/samsung/$model/$rom'
  id:
    | '__root__'
    | '/'
    | '/devices'
    | '/sitemap.xml'
    | '/devices_/samsung'
    | '/devices_/samsung/$model'
    | '/devices_/samsung/$model/$rom'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevicesRoute: typeof DevicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DevicesSamsungRoute: typeof DevicesSamsungRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices_/samsung': {
      id: '/devices_/samsung'
      path: '/devices/samsung'
      fullPath: '/devices/samsung'
      preLoaderRoute: typeof DevicesSamsungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices_/samsung/$model': {
      id: '/devices_/samsung/$model'
      path: '/$model'
      fullPath: '/devices/samsung/$model'
      preLoaderRoute: typeof DevicesSamsungModelRouteImport
      parentRoute: typeof DevicesSamsungRoute
    }
    '/devices_/samsung/$model/$rom': {
      id: '/devices_/samsung/$model/$rom'
      path: '/$rom'
      fullPath: '/devices/samsung/$model/$rom'
      preLoaderRoute: typeof DevicesSamsungModelRomRouteImport
      parentRoute: typeof DevicesSamsungModelRoute
    }
  }
}

interface DevicesSamsungModelRouteChildren {
  DevicesSamsungModelRomRoute: typeof DevicesSamsungModelRomRoute
}

const DevicesSamsungModelRouteChildren: DevicesSamsungModelRouteChildren = {
  DevicesSamsungModelRomRoute: DevicesSamsungModelRomRoute,
}

const DevicesSamsungModelRouteWithChildren =
  DevicesSamsungModelRoute._addFileChildren(DevicesSamsungModelRouteChildren)

interface DevicesSamsungRouteChildren {
  DevicesSamsungModelRoute: typeof DevicesSamsungModelRouteWithChildren
}

const DevicesSamsungRouteChildren: DevicesSamsungRouteChildren = {
  DevicesSamsungModelRoute: DevicesSamsungModelRouteWithChildren,
}

const DevicesSamsungRouteWithChildren = DevicesSamsungRoute._addFileChildren(
  DevicesSamsungRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevicesRoute: DevicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DevicesSamsungRoute: DevicesSamsungRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
